### ISSUE TITLE
crash on Ubuntu 21.10

### ISSUE THREAD

**Issue by itrs** [olleheugene/nRF-DTM#4]
try to run it on Ubuntu 21.10 however it crash at start

➜  ~/download/tmp/nRF_DTM_x64_ubuntu 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(nRF_DTM_x64_ubuntu:451835): GLib-GIO-ERROR **: 13:04:51.383: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
[1]    451833 trace trap (core dumped)  ~/download/tmp/nRF_DTM_x64_ubuntu

**Comment by olleheugene** [comment]
Sorry for the late reply.
I haven't tested the tool on Ubuntu 21.10 before.
It seems to be related to the GTK version by searching on the web.
I am going to test the tool with 21.10 when Ubuntu is ready.

**Comment by olleheugene** [comment]
Sorry again for late update.
Today I've fixed my virtual box installation problem.
So, I tried tested the Ubunu 21.10 version with nRF DTM and finally I fixed the issue.
Please try to check with this version [nRF DTM for Ubuntu 21.10](https://github.com/olleheugene/nRF-DTM/blob/nRF_DTM_Ubuntu_21.10/Release/Ubuntu/nRF_DTM_x64_ubuntu)
I can be worked with 22.04 version as well.
If you find a problem that related MESA-LOADER, then try to use this command on your Ubuntu terminal
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6`
